#!/usr/bin/env bun
// agents-sync v1.0.0 — canonical: grmkris/personal tools/agents-sync/agents-sync.ts
// Keeps one repo's agent config in the standard layout (see infra/agents.md):
//   AGENTS.md (master) ← CLAUDE.md symlink, next to every AGENTS.md
//   .agents/skills/<name> (master) ← .claude/skills/<name> symlink
//   .mcp.json (master) → .codex/config.toml + .cursor/mcp.json (generated)
// Usage: bun scripts/agents-sync.ts [sync|--check|check|doctor|fanout <repo>...] [--force]

import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, relative } from "node:path";

export const VERSION = "1.0.0";
const CODEX_HEADER = `# GENERATED by agents-sync v${VERSION} from .mcp.json — edit .mcp.json, then re-run agents-sync`;
const SKIP_DIRS = new Set([".git", "node_modules", "dist", "build", ".next", ".turbo", ".local", ".crew", ".wrangler"]);

export type McpServer = {
  type?: "stdio" | "http" | "sse";
  url?: string;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  headers?: Record<string, string>;
};

export type Issue = { file: string; problem: string };

// ---------- MCP rendering ----------

const WHOLE_VAR = /^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$/;
const BEARER_VAR = /^Bearer \$\{([A-Za-z_][A-Za-z0-9_]*)\}$/;
const ANY_VAR = /\$\{([^}]*)\}/g;
const SECRETISH = /authorization|token|secret|key|password|cookie/i;

function serverKind(s: McpServer): "stdio" | "http" | "sse" {
  if (s.type) return s.type;
  return s.command ? "stdio" : "http";
}

/** Problems that make a server unsafe or unportable; returned instead of thrown so check can list them all. */
export function validateServers(servers: Record<string, McpServer>): string[] {
  const errors: string[] = [];
  for (const [name, s] of Object.entries(servers)) {
    const kind = serverKind(s);
    if (kind === "sse") errors.push(`${name}: type "sse" is not supported by Codex; use streamable http`);
    if (kind !== "stdio" && !s.url) errors.push(`${name}: http server needs url`);
    if (kind === "stdio" && !s.command) errors.push(`${name}: stdio server needs command`);
    if (s.url && s.url.includes("${")) errors.push(`${name}: \${VAR} inside url cannot be expressed for Codex`);
    const values = [...Object.values(s.headers ?? {}), ...Object.values(s.env ?? {}), ...(s.args ?? [])];
    for (const v of values) {
      for (const m of v.matchAll(ANY_VAR)) {
        if (m[1]?.includes(":-")) errors.push(`${name}: \${VAR:-default} cannot be expressed for Codex/Cursor`);
      }
    }
    for (const [h, v] of Object.entries(s.headers ?? {})) {
      if (SECRETISH.test(h) && !v.includes("${")) errors.push(`${name}: header ${h} has an inline secret; use \${VAR}`);
      if (v.includes("${") && !WHOLE_VAR.test(v) && !BEARER_VAR.test(v)) {
        errors.push(`${name}: header ${h} must be exactly \${VAR} or "Bearer \${VAR}" for Codex`);
      }
    }
    for (const [k, v] of Object.entries(s.env ?? {})) {
      if (SECRETISH.test(k) && !v.includes("${")) errors.push(`${name}: env ${k} has an inline secret; use \${${k}}`);
    }
  }
  return errors;
}

function tomlKey(k: string): string {
  return /^[A-Za-z0-9_-]+$/.test(k) ? k : JSON.stringify(k);
}

function tomlInline(obj: Record<string, string>): string {
  const parts = Object.entries(obj).map(([k, v]) => `${tomlKey(k)} = ${JSON.stringify(v)}`);
  return `{ ${parts.join(", ")} }`;
}

export function renderCodex(servers: Record<string, McpServer>): string {
  const out = [CODEX_HEADER, ""];
  for (const [name, s] of Object.entries(servers)) {
    out.push(`[mcp_servers.${tomlKey(name)}]`);
    if (serverKind(s) === "stdio") {
      out.push(`command = ${JSON.stringify(s.command)}`);
      if (s.args?.length) out.push(`args = [${s.args.map((a) => JSON.stringify(a)).join(", ")}]`);
      const literal: Record<string, string> = {};
      const forwarded: string[] = [];
      for (const [k, v] of Object.entries(s.env ?? {})) {
        const m = WHOLE_VAR.exec(v);
        if (m && m[1] === k) forwarded.push(k);
        else literal[k] = v;
      }
      if (Object.keys(literal).length) out.push(`env = ${tomlInline(literal)}`);
      if (forwarded.length) out.push(`env_vars = [${forwarded.map((k) => JSON.stringify(k)).join(", ")}]`);
    } else {
      out.push(`url = ${JSON.stringify(s.url)}`);
      const fromEnv: Record<string, string> = {};
      const literal: Record<string, string> = {};
      for (const [h, v] of Object.entries(s.headers ?? {})) {
        const bearer = BEARER_VAR.exec(v);
        const whole = WHOLE_VAR.exec(v);
        if (bearer && h.toLowerCase() === "authorization") out.push(`bearer_token_env_var = ${JSON.stringify(bearer[1])}`);
        else if (whole) fromEnv[h] = whole[1]!;
        else literal[h] = v;
      }
      if (Object.keys(literal).length) out.push(`http_headers = ${tomlInline(literal)}`);
      if (Object.keys(fromEnv).length) out.push(`env_http_headers = ${tomlInline(fromEnv)}`);
    }
    out.push("");
  }
  return out.join("\n");
}

const toCursorVars = (v: string) => v.replace(ANY_VAR, (_, name: string) => `\${env:${name}}`);

export function renderCursor(servers: Record<string, McpServer>): string {
  const mcpServers: Record<string, unknown> = {};
  for (const [name, s] of Object.entries(servers)) {
    if (serverKind(s) === "stdio") {
      const entry: Record<string, unknown> = { command: s.command };
      if (s.args?.length) entry.args = s.args.map(toCursorVars);
      if (s.env) entry.env = Object.fromEntries(Object.entries(s.env).map(([k, v]) => [k, toCursorVars(v)]));
      mcpServers[name] = entry;
    } else {
      const entry: Record<string, unknown> = { url: s.url };
      if (s.headers) entry.headers = Object.fromEntries(Object.entries(s.headers).map(([k, v]) => [k, toCursorVars(v)]));
      mcpServers[name] = entry;
    }
  }
  return `${JSON.stringify({ mcpServers }, null, 2)}\n`;
}

// ---------- repo scanning ----------

function listAgentsFiles(root: string): string[] {
  const git = spawnSync("git", ["ls-files", "-co", "--exclude-standard", "--", "AGENTS.md", "**/AGENTS.md"], {
    cwd: root,
    encoding: "utf8",
  });
  if (git.status === 0) {
    return git.stdout
      .split("\n")
      .filter(Boolean)
      .filter((p) => !p.split("/").some((seg) => SKIP_DIRS.has(seg)))
      .filter((p) => existsSync(join(root, p)))
      .sort();
  }
  const found: string[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(join(root, dir), { withFileTypes: true })) {
      if (e.isDirectory() && !SKIP_DIRS.has(e.name)) walk(join(dir, e.name));
      else if (e.isFile() && e.name === "AGENTS.md") found.push(join(dir, e.name));
    }
  };
  walk("");
  return found.sort();
}

function isSymlink(p: string): boolean {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

function linkTarget(p: string): string | null {
  return isSymlink(p) ? readlinkSync(p) : null;
}

function skillNames(root: string): string[] {
  const dir = join(root, ".agents/skills");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, "SKILL.md")))
    .map((e) => e.name)
    .sort();
}

// ---------- plan / apply ----------

type Action =
  | { kind: "write"; file: string; content: string }
  | { kind: "link"; file: string; target: string; replace: boolean }
  | { kind: "unlink"; file: string };

const isStub = (text: string) => text.trim() === "@AGENTS.md" || text.trim() === "";

export function plan(root: string, force = false): { actions: Action[]; issues: Issue[] } {
  const actions: Action[] = [];
  const issues: Issue[] = [];

  // Instructions: CLAUDE.md -> AGENTS.md beside every AGENTS.md.
  for (const agents of listAgentsFiles(root)) {
    const claude = join(dirname(agents), "CLAUDE.md");
    const abs = join(root, claude);
    const target = linkTarget(abs);
    if (target === "AGENTS.md") continue;
    if (target !== null) {
      actions.push({ kind: "link", file: claude, target: "AGENTS.md", replace: true });
    } else if (!existsSync(abs)) {
      actions.push({ kind: "link", file: claude, target: "AGENTS.md", replace: false });
    } else {
      const text = readFileSync(abs, "utf8");
      if (force || isStub(text) || text === readFileSync(join(root, agents), "utf8")) {
        actions.push({ kind: "link", file: claude, target: "AGENTS.md", replace: true });
      } else {
        issues.push({ file: claude, problem: "real file with own content; merge into AGENTS.md (Claude-only bits → .claude/rules/), or --force" });
      }
    }
  }

  // Skills: .claude/skills/<name> -> ../../.agents/skills/<name>.
  const names = skillNames(root);
  const claudeSkills = join(root, ".claude/skills");
  for (const name of names) {
    const file = join(".claude/skills", name);
    const want = join("../../.agents/skills", name);
    const target = linkTarget(join(root, file));
    if (target === want) continue;
    if (target !== null) actions.push({ kind: "link", file, target: want, replace: true });
    else if (existsSync(join(root, file))) issues.push({ file, problem: "real directory; move it to .agents/skills/ (master) and re-run" });
    else actions.push({ kind: "link", file, target: want, replace: false });
  }
  if (existsSync(claudeSkills)) {
    for (const e of readdirSync(claudeSkills)) {
      if (names.includes(e)) continue;
      const file = join(".claude/skills", e);
      const target = linkTarget(join(root, file));
      if (target?.startsWith("../../.agents/skills/")) actions.push({ kind: "unlink", file });
      else issues.push({ file, problem: "not in .agents/skills; move it there (or delete it)" });
    }
  }

  // MCP: .mcp.json -> .codex/config.toml + .cursor/mcp.json.
  const mcpPath = join(root, ".mcp.json");
  if (existsSync(mcpPath)) {
    let servers: Record<string, McpServer> = {};
    try {
      servers = (JSON.parse(readFileSync(mcpPath, "utf8")) as { mcpServers?: Record<string, McpServer> }).mcpServers ?? {};
    } catch (err) {
      issues.push({ file: ".mcp.json", problem: `invalid JSON: ${(err as Error).message}` });
    }
    const errors = validateServers(servers);
    for (const problem of errors) issues.push({ file: ".mcp.json", problem });
    if (errors.length === 0) {
      const outputs: [string, string][] = [
        [".codex/config.toml", renderCodex(servers)],
        [".cursor/mcp.json", renderCursor(servers)],
      ];
      for (const [file, content] of outputs) {
        const abs = join(root, file);
        const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
        if (current === content) continue;
        const ours = current === null || current.startsWith("# GENERATED by agents-sync") || file.endsWith(".json");
        if (!ours && !force) issues.push({ file, problem: "hand-written file; move its servers into .mcp.json, then --force" });
        else actions.push({ kind: "write", file, content });
      }
    }
  }
  return { actions, issues };
}

function apply(root: string, actions: Action[]): void {
  for (const a of actions) {
    const abs = join(root, a.file);
    mkdirSync(dirname(abs), { recursive: true });
    if (a.kind === "write") writeFileSync(abs, a.content);
    else if (a.kind === "unlink") rmSync(abs);
    else {
      if (a.replace) rmSync(abs, { force: true });
      symlinkSync(a.target, abs);
    }
  }
}

const describe = (a: Action) =>
  a.kind === "write" ? `write ${a.file}` : a.kind === "unlink" ? `remove ${a.file}` : `link ${a.file} -> ${a.target}`;

// ---------- doctor / fanout ----------

function doctor(root: string): number {
  console.log(`agents-sync v${VERSION} in ${root}`);
  const mcp = join(root, ".mcp.json");
  if (existsSync(mcp)) {
    const servers = (JSON.parse(readFileSync(mcp, "utf8")) as { mcpServers?: Record<string, McpServer> }).mcpServers ?? {};
    const vars = new Set<string>();
    for (const s of Object.values(servers)) {
      for (const v of [...Object.values(s.headers ?? {}), ...Object.values(s.env ?? {})]) {
        for (const m of v.matchAll(ANY_VAR)) vars.add(m[1]!);
      }
    }
    console.log(`MCP servers: ${Object.keys(servers).join(", ") || "none"}`);
    for (const v of vars) console.log(`  env ${v}: ${process.env[v] ? "set" : "MISSING"}`);
  }
  const home = homedir();
  const leftovers: string[] = [];
  const dirs: [string, (n: string) => boolean][] = [
    [".claude/skills", (n) => n !== "synced"],
    [".agents/skills", () => true],
    [".codex/skills", (n) => n !== ".system"],
    [".grok/skills", () => true],
    [".gemini/skills", () => true],
  ];
  for (const [d, keep] of dirs) {
    const abs = join(home, d);
    if (existsSync(abs)) for (const n of readdirSync(abs).filter(keep)) leftovers.push(`~/${d}/${n}`);
  }
  try {
    const user = JSON.parse(readFileSync(join(home, ".claude.json"), "utf8")) as { mcpServers?: Record<string, unknown> };
    for (const n of Object.keys(user.mcpServers ?? {})) leftovers.push(`~/.claude.json mcpServers.${n}`);
  } catch {}
  console.log(leftovers.length ? `Machine-level leftovers (should be empty):\n  ${leftovers.join("\n  ")}` : "Machine level: clean");
  return 0;
}

function fanout(repos: string[]): number {
  const self = import.meta.path;
  for (const repo of repos) {
    const dest = join(repo, "scripts/agents-sync.ts");
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(self, dest);
    console.log(`copied v${VERSION} -> ${dest}`);
  }
  return 0;
}

// ---------- CLI ----------

export function main(argv: string[], root = process.cwd()): number {
  const force = argv.includes("--force");
  const args = argv.filter((a) => a !== "--force");
  const cmd = args[0] ?? "sync";
  if (cmd === "doctor") return doctor(root);
  if (cmd === "fanout") return fanout(args.slice(1));
  if (cmd !== "sync" && cmd !== "check" && cmd !== "--check") {
    console.error("usage: agents-sync [sync|--check|doctor|fanout <repo>...] [--force]");
    return 2;
  }
  const { actions, issues } = plan(root, force);
  for (const i of issues) console.error(`✗ ${i.file}: ${i.problem}`);
  if (cmd === "sync") {
    apply(root, actions);
    for (const a of actions) console.log(`✓ ${describe(a)}`);
    if (!actions.length && !issues.length) console.log("agents-sync: up to date");
    return issues.length ? 1 : 0;
  }
  for (const a of actions) console.error(`drift: ${describe(a)}`);
  if (!actions.length && !issues.length) console.log(`agents-sync: ok (${relative(process.cwd(), root) || "."})`);
  return actions.length || issues.length ? 1 : 0;
}

if (import.meta.main) process.exit(main(process.argv.slice(2)));
