#!/usr/bin/env bun
// agents-sync v2.0.0 — canonical: grmkris/personal tools/agents-sync/agents-sync.ts
// Keeps one repo's agent config in the standard layout (see infra/agents.md):
//   AGENTS.md (master) ← CLAUDE.md symlink, next to every AGENTS.md
//   .agents/skills/<name> (master) ← .claude/skills/<name> symlink
//   .mcp.json (master) → .codex/config.toml + .cursor/mcp.json (generated)
//   .agents/skills/sources.json (v2) pins vendored skills: upstream commit, license, tree hashes
// Usage: bun scripts/agents-sync.ts [sync|--check|doctor|fanout <repo>...] [--force]
//        bun scripts/agents-sync.ts skills <add|rehash|verify|update [--check]|fanout> ...

import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";

export const VERSION = "2.0.0";
const CODEX_HEADER = `# GENERATED by agents-sync v${VERSION} from .mcp.json — edit .mcp.json, then re-run agents-sync`;
const SKIP_DIRS = new Set([".git", "node_modules", "dist", "build", ".next", ".turbo", ".local", ".crew", ".wrangler"]);

export type McpServer = {
  type?: "stdio" | "http" | "sse";
  url?: string;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  headers?: Record<string, string>;
};

export type Issue = { file: string; problem: string };

// ---------- MCP rendering ----------

const WHOLE_VAR = /^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$/;
const BEARER_VAR = /^Bearer \$\{([A-Za-z_][A-Za-z0-9_]*)\}$/;
const ANY_VAR = /\$\{([^}]*)\}/g;
const SECRETISH = /authorization|token|secret|key|password|cookie/i;

function serverKind(s: McpServer): "stdio" | "http" | "sse" {
  if (s.type) return s.type;
  return s.command ? "stdio" : "http";
}

/** Problems that make a server unsafe or unportable; returned instead of thrown so check can list them all. */
export function validateServers(servers: Record<string, McpServer>): string[] {
  const errors: string[] = [];
  for (const [name, s] of Object.entries(servers)) {
    const kind = serverKind(s);
    if (kind === "sse") errors.push(`${name}: type "sse" is not supported by Codex; use streamable http`);
    if (kind !== "stdio" && !s.url) errors.push(`${name}: http server needs url`);
    if (kind === "stdio" && !s.command) errors.push(`${name}: stdio server needs command`);
    if (s.url && s.url.includes("${")) errors.push(`${name}: \${VAR} inside url cannot be expressed for Codex`);
    const values = [...Object.values(s.headers ?? {}), ...Object.values(s.env ?? {}), ...(s.args ?? [])];
    for (const v of values) {
      for (const m of v.matchAll(ANY_VAR)) {
        if (m[1]?.includes(":-")) errors.push(`${name}: \${VAR:-default} cannot be expressed for Codex/Cursor`);
      }
    }
    for (const [h, v] of Object.entries(s.headers ?? {})) {
      if (SECRETISH.test(h) && !v.includes("${")) errors.push(`${name}: header ${h} has an inline secret; use \${VAR}`);
      if (v.includes("${") && !WHOLE_VAR.test(v) && !BEARER_VAR.test(v)) {
        errors.push(`${name}: header ${h} must be exactly \${VAR} or "Bearer \${VAR}" for Codex`);
      }
    }
    for (const [k, v] of Object.entries(s.env ?? {})) {
      if (SECRETISH.test(k) && !v.includes("${")) errors.push(`${name}: env ${k} has an inline secret; use \${${k}}`);
    }
  }
  return errors;
}

function tomlKey(k: string): string {
  return /^[A-Za-z0-9_-]+$/.test(k) ? k : JSON.stringify(k);
}

function tomlInline(obj: Record<string, string>): string {
  const parts = Object.entries(obj).map(([k, v]) => `${tomlKey(k)} = ${JSON.stringify(v)}`);
  return `{ ${parts.join(", ")} }`;
}

export function renderCodex(servers: Record<string, McpServer>): string {
  const out = [CODEX_HEADER, ""];
  for (const [name, s] of Object.entries(servers)) {
    out.push(`[mcp_servers.${tomlKey(name)}]`);
    if (serverKind(s) === "stdio") {
      out.push(`command = ${JSON.stringify(s.command)}`);
      if (s.args?.length) out.push(`args = [${s.args.map((a) => JSON.stringify(a)).join(", ")}]`);
      const literal: Record<string, string> = {};
      const forwarded: string[] = [];
      for (const [k, v] of Object.entries(s.env ?? {})) {
        const m = WHOLE_VAR.exec(v);
        if (m && m[1] === k) forwarded.push(k);
        else literal[k] = v;
      }
      if (Object.keys(literal).length) out.push(`env = ${tomlInline(literal)}`);
      if (forwarded.length) out.push(`env_vars = [${forwarded.map((k) => JSON.stringify(k)).join(", ")}]`);
    } else {
      out.push(`url = ${JSON.stringify(s.url)}`);
      const fromEnv: Record<string, string> = {};
      const literal: Record<string, string> = {};
      for (const [h, v] of Object.entries(s.headers ?? {})) {
        const bearer = BEARER_VAR.exec(v);
        const whole = WHOLE_VAR.exec(v);
        if (bearer && h.toLowerCase() === "authorization") out.push(`bearer_token_env_var = ${JSON.stringify(bearer[1])}`);
        else if (whole) fromEnv[h] = whole[1]!;
        else literal[h] = v;
      }
      if (Object.keys(literal).length) out.push(`http_headers = ${tomlInline(literal)}`);
      if (Object.keys(fromEnv).length) out.push(`env_http_headers = ${tomlInline(fromEnv)}`);
    }
    out.push("");
  }
  return out.join("\n");
}

const toCursorVars = (v: string) => v.replace(ANY_VAR, (_, name: string) => `\${env:${name}}`);

export function renderCursor(servers: Record<string, McpServer>): string {
  const mcpServers: Record<string, unknown> = {};
  for (const [name, s] of Object.entries(servers)) {
    if (serverKind(s) === "stdio") {
      const entry: Record<string, unknown> = { command: s.command };
      if (s.args?.length) entry.args = s.args.map(toCursorVars);
      if (s.env) entry.env = Object.fromEntries(Object.entries(s.env).map(([k, v]) => [k, toCursorVars(v)]));
      mcpServers[name] = entry;
    } else {
      const entry: Record<string, unknown> = { url: s.url };
      if (s.headers) entry.headers = Object.fromEntries(Object.entries(s.headers).map(([k, v]) => [k, toCursorVars(v)]));
      mcpServers[name] = entry;
    }
  }
  return `${JSON.stringify({ mcpServers }, null, 2)}\n`;
}

// ---------- repo scanning ----------

function listAgentsFiles(root: string): string[] {
  const git = spawnSync("git", ["ls-files", "-co", "--exclude-standard", "--", "AGENTS.md", "**/AGENTS.md"], {
    cwd: root,
    encoding: "utf8",
  });
  if (git.status === 0) {
    return git.stdout
      .split("\n")
      .filter(Boolean)
      .filter((p) => !p.split("/").some((seg) => SKIP_DIRS.has(seg)))
      .filter((p) => existsSync(join(root, p)))
      .sort();
  }
  const found: string[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(join(root, dir), { withFileTypes: true })) {
      if (e.isDirectory() && !SKIP_DIRS.has(e.name)) walk(join(dir, e.name));
      else if (e.isFile() && e.name === "AGENTS.md") found.push(join(dir, e.name));
    }
  };
  walk("");
  return found.sort();
}

function isSymlink(p: string): boolean {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

function linkTarget(p: string): string | null {
  return isSymlink(p) ? readlinkSync(p) : null;
}

function skillNames(root: string): string[] {
  const dir = join(root, ".agents/skills");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, "SKILL.md")))
    .map((e) => e.name)
    .sort();
}

// ---------- plan / apply ----------

type Action =
  | { kind: "write"; file: string; content: string }
  | { kind: "link"; file: string; target: string; replace: boolean }
  | { kind: "unlink"; file: string };

const isStub = (text: string) => text.trim() === "@AGENTS.md" || text.trim() === "";

export function plan(root: string, force = false): { actions: Action[]; issues: Issue[] } {
  const actions: Action[] = [];
  const issues: Issue[] = [];

  // Instructions: CLAUDE.md -> AGENTS.md beside every AGENTS.md.
  for (const agents of listAgentsFiles(root)) {
    const claude = join(dirname(agents), "CLAUDE.md");
    const abs = join(root, claude);
    const target = linkTarget(abs);
    if (target === "AGENTS.md") continue;
    if (target !== null) {
      actions.push({ kind: "link", file: claude, target: "AGENTS.md", replace: true });
    } else if (!existsSync(abs)) {
      actions.push({ kind: "link", file: claude, target: "AGENTS.md", replace: false });
    } else {
      const text = readFileSync(abs, "utf8");
      if (force || isStub(text) || text === readFileSync(join(root, agents), "utf8")) {
        actions.push({ kind: "link", file: claude, target: "AGENTS.md", replace: true });
      } else {
        issues.push({ file: claude, problem: "real file with own content; merge into AGENTS.md (Claude-only bits → .claude/rules/), or --force" });
      }
    }
  }

  // Skills: .claude/skills/<name> -> ../../.agents/skills/<name>.
  const names = skillNames(root);
  const claudeSkills = join(root, ".claude/skills");
  for (const name of names) {
    const file = join(".claude/skills", name);
    const want = join("../../.agents/skills", name);
    const target = linkTarget(join(root, file));
    if (target === want) continue;
    if (target !== null) actions.push({ kind: "link", file, target: want, replace: true });
    else if (existsSync(join(root, file))) issues.push({ file, problem: "real directory; move it to .agents/skills/ (master) and re-run" });
    else actions.push({ kind: "link", file, target: want, replace: false });
  }
  if (existsSync(claudeSkills)) {
    for (const e of readdirSync(claudeSkills)) {
      if (names.includes(e)) continue;
      const file = join(".claude/skills", e);
      const target = linkTarget(join(root, file));
      if (target?.startsWith("../../.agents/skills/")) actions.push({ kind: "unlink", file });
      else issues.push({ file, problem: "not in .agents/skills; move it there (or delete it)" });
    }
  }

  // MCP: .mcp.json -> .codex/config.toml + .cursor/mcp.json.
  const mcpPath = join(root, ".mcp.json");
  if (existsSync(mcpPath)) {
    let servers: Record<string, McpServer> = {};
    try {
      servers = (JSON.parse(readFileSync(mcpPath, "utf8")) as { mcpServers?: Record<string, McpServer> }).mcpServers ?? {};
    } catch (err) {
      issues.push({ file: ".mcp.json", problem: `invalid JSON: ${(err as Error).message}` });
    }
    const errors = validateServers(servers);
    for (const problem of errors) issues.push({ file: ".mcp.json", problem });
    if (errors.length === 0) {
      const outputs: [string, string][] = [
        [".codex/config.toml", renderCodex(servers)],
        [".cursor/mcp.json", renderCursor(servers)],
      ];
      for (const [file, content] of outputs) {
        const abs = join(root, file);
        const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
        if (current === content) continue;
        const ours = current === null || current.startsWith("# GENERATED by agents-sync") || file.endsWith(".json");
        if (!ours && !force) issues.push({ file, problem: "hand-written file; move its servers into .mcp.json, then --force" });
        else actions.push({ kind: "write", file, content });
      }
    }
  }
  return { actions, issues };
}

function apply(root: string, actions: Action[]): void {
  for (const a of actions) {
    const abs = join(root, a.file);
    mkdirSync(dirname(abs), { recursive: true });
    if (a.kind === "write") writeFileSync(abs, a.content);
    else if (a.kind === "unlink") rmSync(abs);
    else {
      if (a.replace) rmSync(abs, { force: true });
      symlinkSync(a.target, abs);
    }
  }
}

const describe = (a: Action) =>
  a.kind === "write" ? `write ${a.file}` : a.kind === "unlink" ? `remove ${a.file}` : `link ${a.file} -> ${a.target}`;

// ---------- vendored skills (.agents/skills/sources.json v2) ----------

export type SkillSource = {
  repository: string; // owner/repo on GitHub
  commit: string; // pinned upstream commit
  path: string; // skill dir inside the upstream repo
  license: string; // SPDX id
  licenses: string[]; // license files inside the vendored dir
  treeSha256: string; // hash of the files as copied from upstream
  localTreeSha256: string; // hash of the committed dir
  unchanged: boolean; // local === upstream copy
  adaptation?: string; // why and how the copy differs (required when !unchanged)
  baseCommit?: string; // upstream commit the adaptation was made on
};
export type SourcesFile = { version: 2; skills: Record<string, SkillSource> };

const SOURCES = ".agents/skills/sources.json";
const LICENSE_RE = /^(LICENSE|LICENCE|COPYING|NOTICE)(\.[a-z]+)?$/i;

/** sha256 over sorted relative paths + bytes (same idea as vercel-labs/skills computeSkillFolderHash). */
export function treeHash(dir: string): string {
  const hash = new Bun.CryptoHasher("sha256");
  const files: string[] = [];
  const walk = (rel: string) => {
    for (const e of readdirSync(join(dir, rel), { withFileTypes: true })) {
      if (e.name === ".git" || e.name === "node_modules") continue;
      const p = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory()) walk(p);
      else if (e.isFile()) files.push(p);
    }
  };
  walk("");
  for (const f of files.sort()) {
    hash.update(f);
    hash.update("\0");
    hash.update(readFileSync(join(dir, f)));
    hash.update("\0");
  }
  return hash.digest("hex");
}

export function readSources(root: string): SourcesFile {
  const p = join(root, SOURCES);
  if (!existsSync(p)) return { version: 2, skills: {} };
  const raw = JSON.parse(readFileSync(p, "utf8")) as { version?: number; skills?: Record<string, SkillSource> };
  return { version: 2, skills: raw.skills ?? {} };
}

function writeSources(root: string, s: SourcesFile): void {
  const sorted = Object.fromEntries(Object.entries(s.skills).sort(([a], [b]) => a.localeCompare(b)));
  mkdirSync(join(root, ".agents/skills"), { recursive: true });
  writeFileSync(join(root, SOURCES), `${JSON.stringify({ version: 2, skills: sorted }, null, 2)}\n`);
}

function detectLicense(text: string): string {
  if (/Apache License[\s\S]*Version 2\.0/i.test(text)) return "Apache-2.0";
  if (/Attribution-ShareAlike 4\.0/i.test(text)) return "CC-BY-SA-4.0";
  if (/GNU AFFERO GENERAL PUBLIC LICENSE/i.test(text)) return "AGPL-3.0";
  if (/Permission is hereby granted, free of charge/i.test(text)) return "MIT";
  if (/BSD/i.test(text)) return "BSD";
  return "UNKNOWN";
}

/** owner/repo → GitHub URL; absolute paths and URLs pass through (tests use a local repo). */
const repoUrl = (repository: string) =>
  repository.includes("://") || repository.startsWith("/") ? repository : `https://github.com/${repository}.git`;

function git(args: string[], cwd: string): string {
  const r = spawnSync("git", args, { cwd, encoding: "utf8" });
  if (r.status !== 0) throw new Error(`git ${args.join(" ")}: ${r.stderr.trim()}`);
  return r.stdout.trim();
}

/** Sparse, shallow fetch of one path (plus root license files) at ref; returns the checkout dir and resolved commit. */
function fetchUpstream(repository: string, path: string, ref = "HEAD"): { dir: string; commit: string } {
  const dir = mkdtempSync(join(tmpdir(), "agents-sync-"));
  git(["init", "-q"], dir);
  git(["remote", "add", "origin", repoUrl(repository)], dir);
  // path "." vendors the whole repo (skills whose SKILL.md sits at the repo root)
  if (path !== ".") {
    // also fetch license files of every ancestor dir (plugin repos keep LICENSE beside the plugin, not at root)
    const parts = path.split("/");
    const ancestors = parts.slice(0, -1).map((_, i) => `/${parts.slice(0, i + 1).join("/")}`);
    const lic = ["", ...ancestors].flatMap((a) => ["LICENSE*", "LICENCE*", "COPYING*", "NOTICE*"].map((f) => `${a}/${f}`));
    git(["sparse-checkout", "set", "--no-cone", `/${path}/`, ...lic], dir);
  }
  git(["fetch", "-q", "--depth", "1", "--filter=blob:none", "origin", ref], dir);
  git(["checkout", "-q", "FETCH_HEAD"], dir);
  return { dir, commit: git(["rev-parse", "HEAD"], dir) };
}

/** Copy an upstream skill into dest; adds the repo license when the skill dir has none. Returns license info. */
function copySkill(checkout: string, path: string, dest: string): { license: string; licenses: string[] } {
  rmSync(dest, { recursive: true, force: true });
  const src = join(checkout, path);
  if (!existsSync(join(src, "SKILL.md"))) throw new Error(`${path}/SKILL.md not found upstream`);
  const copyDir = (from: string, to: string) => {
    mkdirSync(to, { recursive: true });
    for (const e of readdirSync(from, { withFileTypes: true })) {
      if (e.name === ".git" || e.name === ".agents-sync-copy") continue;
      if (e.isDirectory()) copyDir(join(from, e.name), join(to, e.name));
      else if (e.isFile()) copyFileSync(join(from, e.name), join(to, e.name));
    }
  };
  copyDir(src, dest);
  let licenses = readdirSync(dest).filter((f) => LICENSE_RE.test(f));
  // nearest ancestor license wins (plugin dir before repo root)
  const parts = path === "." ? [] : path.split("/").slice(0, -1);
  for (let i = parts.length; !licenses.length && i >= 0; i--) {
    const at = join(checkout, ...parts.slice(0, i));
    if (!existsSync(at)) continue;
    for (const f of readdirSync(at).filter((n) => LICENSE_RE.test(n))) copyFileSync(join(at, f), join(dest, f));
    licenses = readdirSync(dest).filter((f) => LICENSE_RE.test(f));
  }
  const text = licenses.map((f) => readFileSync(join(dest, f), "utf8")).join("\n");
  return { license: licenses.length ? detectLicense(text) : "UNKNOWN", licenses };
}

export function skillsAdd(root: string, repository: string, path: string, opts: { ref?: string; name?: string; license?: string } = {}): string {
  const name = opts.name ?? (path === "." ? repository.split("/").pop()! : path.split("/").pop()!);
  const { dir, commit } = fetchUpstream(repository, path, opts.ref);
  try {
    const dest = join(root, ".agents/skills", name);
    const lic = copySkill(dir, path, dest);
    const hash = treeHash(dest);
    const s = readSources(root);
    s.skills[name] = {
      repository,
      commit,
      path,
      license: opts.license ?? lic.license,
      licenses: lic.licenses,
      treeSha256: hash,
      localTreeSha256: hash,
      unchanged: true,
    };
    writeSources(root, s);
    return `${name} @ ${repository}@${commit.slice(0, 7)} (${opts.license ?? lic.license})`;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Record local edits to a vendored skill: recompute its hash and mark it adapted. */
export function skillsRehash(root: string, name: string, adaptation?: string): void {
  const s = readSources(root);
  const e = s.skills[name];
  if (!e) throw new Error(`${name} is not in ${SOURCES}`);
  e.localTreeSha256 = treeHash(join(root, ".agents/skills", name));
  e.unchanged = e.localTreeSha256 === e.treeSha256;
  if (!e.unchanged) {
    e.adaptation = adaptation ?? e.adaptation;
    e.baseCommit = e.commit;
    if (!e.adaptation) throw new Error(`${name} differs from upstream: pass the adaptation reason`);
  } else {
    delete e.adaptation;
    delete e.baseCommit;
  }
  writeSources(root, s);
}

/** Offline checks for vendored skills; returned as issues so --check can list them. */
export function skillsVerify(root: string): Issue[] {
  const issues: Issue[] = [];
  const s = readSources(root);
  for (const [name, e] of Object.entries(s.skills)) {
    const dir = join(root, ".agents/skills", name);
    const file = `.agents/skills/${name}`;
    if (!existsSync(join(dir, "SKILL.md"))) {
      issues.push({ file, problem: "listed in sources.json but missing" });
      continue;
    }
    for (const f of ["repository", "commit", "path", "license", "treeSha256", "localTreeSha256"] as const) {
      if (!e[f]) issues.push({ file, problem: `sources.json entry lacks ${f} (re-add with: agents-sync skills add)` });
    }
    for (const l of e.licenses ?? []) if (!existsSync(join(dir, l))) issues.push({ file, problem: `license file ${l} missing` });
    if (!e.licenses?.length) issues.push({ file, problem: "no license file vendored" });
    const now = treeHash(dir);
    if (e.localTreeSha256 && now !== e.localTreeSha256) {
      issues.push({ file, problem: "edited since it was recorded; run: agents-sync skills rehash <name> \"<why>\"" });
    }
    if (e.unchanged && e.localTreeSha256 !== e.treeSha256) issues.push({ file, problem: "marked unchanged but differs from upstream" });
    if (!e.unchanged && !e.adaptation) issues.push({ file, problem: "adapted without an adaptation note" });
  }
  return issues;
}

/** Compare pins with upstream HEAD; with apply, re-vendor unchanged skills (adapted ones are reported only). */
export function skillsUpdate(root: string, only: string[], apply: boolean): number {
  const s = readSources(root);
  let outdated = 0;
  for (const [name, e] of Object.entries(s.skills)) {
    if (only.length && !only.includes(name)) continue;
    const head = git(["ls-remote", repoUrl(e.repository), "HEAD"], root).split(/\s/)[0]!;
    if (head === e.commit) {
      console.log(`✓ ${name}: current (${head.slice(0, 7)})`);
      continue;
    }
    const { dir } = fetchUpstream(e.repository, e.path, head);
    try {
      const tmp = join(dir, ".agents-sync-copy");
      copySkill(dir, e.path, tmp);
      const upstream = treeHash(tmp);
      if (upstream === e.treeSha256) {
        console.log(`✓ ${name}: current (repo moved to ${head.slice(0, 7)}, skill unchanged)`);
        if (apply) {
          const fresh = readSources(root);
          fresh.skills[name]!.commit = head;
          writeSources(root, fresh);
        }
        continue;
      }
      outdated++;
      if (!apply) console.log(`↑ ${name}: upstream changed (${e.commit.slice(0, 7)} → ${head.slice(0, 7)})`);
      else if (e.unchanged) console.log(`✓ ${name}: updated → ${skillsAdd(root, e.repository, e.path, { ref: head, name, license: e.license })}`);
      else console.log(`! ${name}: adapted locally; review upstream ${e.commit.slice(0, 7)}..${head.slice(0, 7)} for ${e.path} and re-apply by hand`);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }
  return apply ? 0 : outdated ? 1 : 0;
}

/** Copy vendored skills (dir + sources entry) from this repo into other repos. */
export function skillsFanout(root: string, names: string[], targets: string[]): void {
  const s = readSources(root);
  for (const target of targets) {
    const t = readSources(target);
    for (const name of names) {
      const src = join(root, ".agents/skills", name);
      if (!existsSync(join(src, "SKILL.md"))) throw new Error(`${name} not found in ${root}`);
      const dest = join(target, ".agents/skills", name);
      rmSync(dest, { recursive: true, force: true });
      mkdirSync(dirname(dest), { recursive: true });
      const cp = spawnSync("cp", ["-R", src, dest]);
      if (cp.status !== 0) throw new Error(`copy ${name} -> ${target} failed`);
      if (s.skills[name]) t.skills[name] = { ...s.skills[name] };
      else delete t.skills[name];
      console.log(`copied ${name} -> ${target}`);
    }
    writeSources(target, t);
  }
}

function skillsCli(root: string, args: string[]): number {
  const [sub, ...rest] = args;
  const flag = (n: string) => {
    const i = rest.indexOf(n);
    if (i < 0) return undefined;
    const v = rest[i + 1];
    rest.splice(i, 2);
    return v;
  };
  try {
    if (sub === "add") {
      const ref = flag("--ref");
      const name = flag("--name");
      const license = flag("--license");
      const [repository, path] = rest;
      if (!repository || !path) throw new Error("usage: skills add <owner/repo> <path> [--ref sha] [--name n] [--license spdx]");
      console.log(`✓ ${skillsAdd(root, repository, path, { ref, name, license })}`);
      return 0;
    }
    if (sub === "rehash") {
      skillsRehash(root, rest[0]!, rest[1]);
      console.log(`✓ ${rest[0]} recorded`);
      return 0;
    }
    if (sub === "verify") {
      const issues = skillsVerify(root);
      for (const i of issues) console.error(`✗ ${i.file}: ${i.problem}`);
      if (!issues.length) console.log(`skills: ok (${Object.keys(readSources(root).skills).length} vendored)`);
      return issues.length ? 1 : 0;
    }
    if (sub === "update") {
      const check = rest.includes("--check");
      return skillsUpdate(root, rest.filter((a) => a !== "--check"), !check);
    }
    if (sub === "fanout") {
      const to = rest.indexOf("--to");
      if (to < 1) throw new Error("usage: skills fanout <name>... --to <repo>...");
      skillsFanout(root, rest.slice(0, to), rest.slice(to + 1));
      return 0;
    }
    throw new Error("usage: agents-sync skills <add|rehash|verify|update [--check]|fanout> ...");
  } catch (err) {
    console.error(`✗ ${(err as Error).message}`);
    return 1;
  }
}

// ---------- doctor / fanout ----------

function doctor(root: string): number {
  console.log(`agents-sync v${VERSION} in ${root}`);
  const mcp = join(root, ".mcp.json");
  if (existsSync(mcp)) {
    const servers = (JSON.parse(readFileSync(mcp, "utf8")) as { mcpServers?: Record<string, McpServer> }).mcpServers ?? {};
    const vars = new Set<string>();
    for (const s of Object.values(servers)) {
      for (const v of [...Object.values(s.headers ?? {}), ...Object.values(s.env ?? {})]) {
        for (const m of v.matchAll(ANY_VAR)) vars.add(m[1]!);
      }
    }
    console.log(`MCP servers: ${Object.keys(servers).join(", ") || "none"}`);
    // @effect-diagnostics-next-line processEnv:off -- a one-shot config check reports which MCP env vars are set, never their values
    for (const v of vars) console.log(`  env ${v}: ${process.env[v] ? "set" : "MISSING"}`);
  }
  const home = homedir();
  const leftovers: string[] = [];
  const dirs: [string, (n: string) => boolean][] = [
    [".claude/skills", (n) => n !== "synced"],
    [".agents/skills", () => true],
    [".codex/skills", (n) => n !== ".system"],
    [".grok/skills", () => true],
    [".gemini/skills", () => true],
  ];
  for (const [d, keep] of dirs) {
    const abs = join(home, d);
    if (existsSync(abs)) for (const n of readdirSync(abs).filter(keep)) leftovers.push(`~/${d}/${n}`);
  }
  try {
    const user = JSON.parse(readFileSync(join(home, ".claude.json"), "utf8")) as { mcpServers?: Record<string, unknown> };
    for (const n of Object.keys(user.mcpServers ?? {})) leftovers.push(`~/.claude.json mcpServers.${n}`);
  } catch {}
  console.log(leftovers.length ? `Machine-level leftovers (should be empty):\n  ${leftovers.join("\n  ")}` : "Machine level: clean");
  return 0;
}

function fanout(repos: string[]): number {
  const self = import.meta.path;
  for (const repo of repos) {
    const dest = join(repo, "scripts/agents-sync.ts");
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(self, dest);
    console.log(`copied v${VERSION} -> ${dest}`);
  }
  return 0;
}

// ---------- CLI ----------

export function main(argv: string[], root = process.cwd()): number {
  const force = argv.includes("--force");
  const args = argv.filter((a) => a !== "--force");
  const cmd = args[0] ?? "sync";
  if (cmd === "doctor") return doctor(root);
  if (cmd === "fanout") return fanout(args.slice(1));
  if (cmd === "skills") return skillsCli(root, args.slice(1));
  if (cmd !== "sync" && cmd !== "check" && cmd !== "--check") {
    console.error("usage: agents-sync [sync|--check|doctor|fanout <repo>...|skills ...] [--force]");
    return 2;
  }
  const planned = plan(root, force);
  const actions = planned.actions;
  const issues = [...planned.issues, ...skillsVerify(root)];
  for (const i of issues) console.error(`✗ ${i.file}: ${i.problem}`);
  if (cmd === "sync") {
    apply(root, actions);
    for (const a of actions) console.log(`✓ ${describe(a)}`);
    if (!actions.length && !issues.length) console.log("agents-sync: up to date");
    return issues.length ? 1 : 0;
  }
  for (const a of actions) console.error(`drift: ${describe(a)}`);
  if (!actions.length && !issues.length) console.log(`agents-sync: ok (${relative(process.cwd(), root) || "."})`);
  return actions.length || issues.length ? 1 : 0;
}

if (import.meta.main) process.exit(main(process.argv.slice(2)));
