#!/usr/bin/env python3
"""Derive a mesh-free URDF for kinematics.

The SO-101 URDF references 15 MB of STL meshes that are deliberately gitignored,
so a fresh checkout cannot load it and placo refuses outright ("Mesh ... could
not be found"). FK and IK need only the joint tree, origins and inertials -- the
visual and collision geometry is dead weight for solving.

Output is a few KB and safe to commit, so the room host gets working kinematics
straight from `git pull`.

    python scripts/make_kinematics_urdf.py \
        phone_teleop/SO101/so101_new_calib.urdf phone_teleop/SO101/so101_kinematics.urdf
"""

import sys
import xml.etree.ElementTree as ET


def strip(src: str, dst: str) -> tuple[int, int]:
    tree = ET.parse(src)
    root = tree.getroot()
    removed = 0
    for link in root.iter("link"):
        for tag in ("visual", "collision"):
            for el in list(link.findall(tag)):
                link.remove(el)
                removed += 1
    root.insert(0, ET.Comment(
        " Generated by scripts/make_kinematics_urdf.py from so101_new_calib.urdf. "
        "Visual/collision geometry stripped so kinematics works without the "
        "gitignored STL assets. Do not hand-edit; regenerate. "))
    ET.indent(tree, space="  ")
    tree.write(dst, encoding="utf-8", xml_declaration=True)
    return removed, len(root.findall("joint"))


if __name__ == "__main__":
    src, dst = sys.argv[1], sys.argv[2]
    n, joints = strip(src, dst)
    print(f"stripped {n} visual/collision elements, kept {joints} joints -> {dst}")
