"""Generate dimensioned SVG board artwork, fiducial tabs and a build report."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "chess_system" / "config" / "chess_geometry.json"
OUT = ROOT / "chess_system" / "fabrication" / "generated"


def marker_bits(marker_id: int, size: int = 6) -> list[list[int]]:
    """Return an OpenCV 4x4 marker including its one-cell black border."""

    try:
        import cv2
    except ImportError as exc:
        raise SystemExit(
            "OpenCV with aruco support is required; run with the pinned driver environment"
        ) from exc
    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    image = cv2.aruco.generateImageMarker(dictionary, marker_id, size)
    return [[1 if int(pixel) < 128 else 0 for pixel in row] for row in image]


def svg_marker(bits: list[list[int]], x: float, y: float, size: float) -> str:
    cell = size / len(bits)
    rects = [f'<rect x="{x}" y="{y}" width="{size}" height="{size}" fill="white"/>']
    for row, values in enumerate(bits):
        for col, black in enumerate(values):
            if black:
                rects.append(
                    f'<rect x="{x + col * cell:.4f}" y="{y + row * cell:.4f}" '
                    f'width="{cell:.4f}" height="{cell:.4f}" fill="black"/>'
                )
    return "\n".join(rects)


def board_svg(spec: dict) -> str:
    board = spec["board"]
    square = board["square_size"] * 1000
    carrier = board["carrier_size"][0] * 1000
    playfield = square * 8
    margin = (carrier - playfield) / 2
    page = 280.0
    board_x = (page - carrier) / 2
    board_y = (page - carrier) / 2
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{page}mm" height="{page}mm" viewBox="0 0 {page} {page}">',
        '<rect width="100%" height="100%" fill="white"/>',
        f'<rect x="{board_x}" y="{board_y}" width="{carrier}" height="{carrier}" fill="#171a1d" stroke="black" stroke-width="0.3"/>',
    ]
    colors = ("#d8c49a", "#3d5148")
    for visual_rank in range(8):
        for file_index in range(8):
            x = board_x + margin + file_index * square
            y = board_y + margin + visual_rank * square
            color = colors[(visual_rank + file_index) % 2]
            parts.append(f'<rect x="{x}" y="{y}" width="{square}" height="{square}" fill="{color}"/>')
    for file_index, name in enumerate("abcdefgh"):
        x = board_x + margin + (file_index + 0.5) * square
        parts.append(f'<text x="{x}" y="{board_y + margin - 2.2}" text-anchor="middle" font-size="4" fill="white">{name}</text>')
        parts.append(f'<text x="{x}" y="{board_y + margin + playfield + 6}" text-anchor="middle" font-size="4" fill="white">{name}</text>')
    for visual_rank in range(8):
        rank = 8 - visual_rank
        y = board_y + margin + (visual_rank + 0.5) * square + 1.4
        parts.append(f'<text x="{board_x + margin - 4}" y="{y}" text-anchor="middle" font-size="4" fill="white">{rank}</text>')
        parts.append(f'<text x="{board_x + margin + playfield + 4}" y="{y}" text-anchor="middle" font-size="4" fill="white">{rank}</text>')

    marker_size = board["fiducial_size"] * 1000
    marker_positions = ((5, 5), (page - marker_size - 5, 5), (page - marker_size - 5, page - marker_size - 5), (5, page - marker_size - 5))
    for marker_id, (x, y) in enumerate(marker_positions):
        parts.append(svg_marker(marker_bits(marker_id), x, y, marker_size))
        parts.append(f'<text x="{x + marker_size / 2}" y="{y + marker_size + 4}" text-anchor="middle" font-size="3">ID {marker_id}</text>')

    parts.extend(
        [
            f'<line x1="{board_x}" y1="{board_y - 5}" x2="{board_x + carrier}" y2="{board_y - 5}" stroke="#d22" stroke-width="0.3"/>',
            f'<text x="{page/2}" y="{board_y - 7}" text-anchor="middle" font-size="4" fill="#d22">{carrier:.0f} mm carrier / {square:.0f} mm squares — print at 100%</text>',
            '<text x="140" y="276" text-anchor="middle" font-size="3.5">SO-101 MICRO-CHESS · verify the 100 mm scale bar before bonding</text>',
            '<line x1="90" y1="268" x2="190" y2="268" stroke="black" stroke-width="1"/>',
            '<line x1="90" y1="265" x2="90" y2="271" stroke="black" stroke-width="1"/>',
            '<line x1="190" y1="265" x2="190" y2="271" stroke="black" stroke-width="1"/>',
            '</svg>',
        ]
    )
    return "\n".join(parts)


def dimension_report(spec: dict) -> str:
    board = spec["board"]
    piece = spec["piece"]
    tool = spec["tool"]
    return f"""# Generated fabrication dimensions

Generated from `chess_system/config/chess_geometry.json`. Do not edit this file by hand.

| Item | Dimension |
|---|---:|
| Playfield | {board['square_size'] * board['files'] * 1000:.0f} × {board['square_size'] * board['ranks'] * 1000:.0f} mm |
| Square pitch | {board['square_size'] * 1000:.1f} mm |
| Carrier | {board['carrier_size'][0] * 1000:.0f} × {board['carrier_size'][1] * 1000:.0f} × {board['carrier_size'][2] * 1000:.1f} mm |
| Pivot → playfield near edge | {board['playfield_near_x'] * 1000:.1f} mm |
| Piece base | Ø {piece['base_diameter'] * 1000:.1f} mm |
| Piece height | {piece['total_height'] * 1000:.1f} mm |
| Grasp mast | Ø {piece['grasp_mast_diameter'] * 1000:.1f} × {piece['grasp_mast_height'] * 1000:.1f} mm |
| Finger-extension nominal length | {tool['extension_length'] * 1000:.1f} mm |
| Finger tip | {tool['tip_thickness'] * 1000:.1f} × {tool['tip_width'] * 1000:.1f} mm |
| Maximum open tool envelope | {tool['maximum_open_outer_width'] * 1000:.1f} mm |

The generated extension roots are fit-check prototypes. Print the crowded coupon and extensions before the complete set; adjust only the keyed root to the measured jaws, not the tip envelope or board pitch.
"""


def main() -> None:
    with CONFIG.open(encoding="utf-8") as handle:
        spec = json.load(handle)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "micro_chess_board.svg").write_text(board_svg(spec), encoding="utf-8")
    (OUT / "DIMENSIONS.md").write_text(dimension_report(spec), encoding="utf-8")
    print(f"generated board artwork and dimension report in {OUT}")


if __name__ == "__main__":
    main()
